# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WA07_Xu_9492' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WA07_Xu_9492
  pod 'Alamofire'  

  target 'WA07_Xu_9492Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WA07_Xu_9492UITests' do
    # Pods for testing
  end

end
